spring.application.name=planner
# 1. 데이터베이스 연결 설정 (MariaDB)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/planner?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=1234

# 2. JPA (데이터베이스 조작 도구) 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. 외부 환경 변수 및 보안 파일 연결 설정
# application-secret.yml 파일에 숨겨둔 API 키 값들을 서버 실행 시 함께 불러옵니다.
spring.profiles.include=secret

# 4. Swagger API 문서 접속 주소 설정
springdoc.swagger-ui.path=/api-docs

# 5. JWT Secret Key (서버만의 위조 방지 비밀 도장)
jwt.secret=TravelPlannerProjectSuperSecretKeyMadeByDonghwi2026!@#